# Generated by Django 5.2 on 2025-10-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotions_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
