version: '3.9'

services:
  web:
    build: .
    command: uvicorn easymart.asgi:application --host 0.0.0.0 --port 8000 --workers 3
    env_file: .env
    expose:
      - "8000"
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  default:
    name: easymart_network