# Generated by Django 5.2 on 2025-10-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevents',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('search', 'Search')], max_length=20),
        ),
    ]
