# Generated by Django 5.2 on 2025-10-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticsevents_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrankingmetrics',
            name='metric_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('views', 'Views'), ('add_to_cart', 'Add To Cart'), ('wishlist_adds', 'Wishlist Adds'), ('search_click', 'Search Click')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productrankingmetrics',
            name='time_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productrankings',
            name='time_period',
            field=models.CharField(choices=[('ranking_type', 'best_selling trending top_selling')], max_length=20),
        ),
    ]
