# Generated by Django 5.2 on 2025-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_productrankingmetrics_metric_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrankings',
            name='ranking_type',
            field=models.CharField(choices=[('best_selling', 'Best Selling'), ('trending', 'Trending'), ('top_selling', 'Top Selling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productrankings',
            name='time_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20),
        ),
    ]
