# Generated by Django 5.2 on 2025-10-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_productrankings_ranking_type_and_more'),
        ('products', '0011_alter_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevents',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_product_id', to='products.product'),
        ),
    ]
