
upstream django {
  server web:8000;
}

server {
  listen 80;
  server_name localhost;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location /static/ {
    alias https://easymartaqo.s3.amazonaws.com/static/;
    expires 30d;
    add_header Cache-Control "public, immutable";
  }

  location /media/ {
    alias https://easymartaqo.s3.amazonaws.com/media/;
  }

  location /ws/ {
    proxy_pass http://django;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://django;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
