version = 5.2.2
archive_dir = /etc/letsencrypt/archive/easymartapi.aqoprojects.com
cert = /etc/letsencrypt/live/easymartapi.aqoprojects.com/cert.pem
privkey = /etc/letsencrypt/live/easymartapi.aqoprojects.com/privkey.pem
chain = /etc/letsencrypt/live/easymartapi.aqoprojects.com/chain.pem
fullchain = /etc/letsencrypt/live/easymartapi.aqoprojects.com/fullchain.pem
[renewalparams]
account = 2c4ca5a88347fd7b0652ca67f8db872f
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
easymartapi.aqoprojects.com = /var/www/certbot
www.easymartapi.aqoprojects.com = /var/www/certbot
