# Generated by Django 5.2 on 2025-11-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_cart_id'),
        ('products', '0011_alter_product_product_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart_id', 'product_id')},
        ),
    ]
