# Generated by Django 5.2 on 2025-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
