# Generated by Django 5.2 on 2025-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimages_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
