# Generated by Django 5.2 on 2025-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimages_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_url',
            field=models.ImageField(max_length=500, upload_to='products/'),
        ),
    ]
