# Generated by Django 5.2 on 2025-10-17 17:01

import django.core.validators
import utils.products.validators.catgeoryIcons
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Icon',
            field=models.ImageField(blank=True, null=True, upload_to='categoryIcon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), utils.products.validators.catgeoryIcons.validate_Icon_size]),
        ),
    ]
